name: usps_sdk
description: United States Postal Service unofficial Software Development Kit
version: 0.0.3

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  sexy_api_client: ^0.0.6+6
  xml_parser: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
